services:
  idx-dashboard: 
    container_name: idx-dashboard
    image: idx-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile.prebuilt
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
